# Generated by Django 6.0.2 on 2026-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_team_id_team_guide_team_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
