# Generated by Django 6.0.2 on 2026-02-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_documentslot_teamsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentslot',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentslot',
            name='slot_type',
            field=models.CharField(choices=[('PROPOSAL', 'Project Proposal'), ('REPORT', 'Final Report'), ('OTHER', 'General Submission')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='r1_coord_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='r1_guide_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='r1_hod_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='r2_coord_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='r2_guide_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='r2_hod_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='report_coord_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='report_guide_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='team',
            name='report_hod_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
