# Generated by Django 6.0.2 on 2026-02-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teammember_attendance_marks_teammember_r1_c_absent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='r1_coord_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r1_guide_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r1_hod_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r2_coord_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r2_guide_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='r2_hod_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='report_coord_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='report_guide_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='report_hod_marks',
        ),
    ]
