# Generated by Django 6.0.2 on 2026-02-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teammember_attendance_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentslot',
            name='slot_type',
            field=models.CharField(choices=[('PROPOSAL', 'Project Proposal'), ('ABSTRACT', 'Abstract'), ('SRS', 'SRS Document'), ('PPT1', 'Presentation 1 (PPT)'), ('PPT2', 'Presentation 2 (PPT)'), ('REPORT', 'Final Project Report')], default='OTHER', max_length=20),
        ),
    ]
