# Generated by Django 6.0.2 on 2026-02-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_teammember_r1_c_total_teammember_r1_g_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='r1_c_total',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='r1_g_total',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='r1_h_total',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='r2_c_total',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='r2_g_total',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='r2_h_total',
        ),
    ]
