# Generated by Django 6.0.2 on 2026-02-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_teammember_r1_coord_total_teammember_r1_guide_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentslot',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
