# Generated by Django 6.0.2 on 2026-03-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
