# Generated by Django 6.0.2 on 2026-03-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_documentslot_slot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentslot',
            name='slot_type',
            field=models.CharField(choices=[('PROPOSAL', 'Project Proposal'), ('ABSTRACT', 'Abstract'), ('SRS', 'SRS Document'), ('FINAL_PPT', 'Final PPT'), ('REPORT', 'Final Project Report')], default='OTHER', max_length=20),
        ),
    ]
