# Generated by Django 6.0.2 on 2026-03-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_documentslot_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsubmission',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
