# Generated by Django 6.0.2 on 2026-03-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_teamsubmission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsubmission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
